language: node_js
node_js:
  - 11

env:
 - IMAGE_NAME=868894423383.dkr.ecr.eu-west-1.amazonaws.com/juice-shop:1.0-$TRAVIS_BUILD_NUMBER
services:
  - docker

script:
  - echo 'Use Docker!'

after_success:
  - pip install --user awscli
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameter-override ImageName=$IMAGE_NAME
  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=$IMAGE_NAME"
