language: node_js
node_js:
  - 11

env:
 - IMAGE_NAME=529455930136.dkr.ecr.us-east-2.amazonaws.com/isentest
services:
  - docker
  
before_script:
  - mkdir -p $HOME/bin
  - wget https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-5.0.0-M3-release.zip -O $HOME/bin/dc.zip
  - cd $HOME/bin/ && unzip dc.zip
  - cd -

script:
  - echo 'Use Docker!'
  - sonar-scanner
  - npm install
  - $HOME/bin/dependency-check/bin/dependency-check.sh --project juice-shop -s . 
  
addons:
  sonarcloud:
    organization: "nahyk-github" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

after_success:
  - pip install --user awscli
  - eval $(aws ecr get-login --region us-east-2 --no-include-email)
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region us-east-2 --parameter-override ImageName=$IMAGE_NAME
  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region us-east-2 --parameters "ParameterKey=ImageName,ParameterValue=$IMAGE_NAME"
